### ISSUE TITLE
萌虎摇摇乐  入口在哪

### ISSUE THREAD

**Issue by pycgo** [LingFeng0918/jd_scripts#11]

**Comment by LingFeng0918** [comment]
https://yearfestival.jd.com/#/


***@***.***
 
发件人： pycgo
发送时间： 2022-01-26 09:51
收件人： LingFeng0918/jd_scripts
抄送： Subscribed
主题： [LingFeng0918/jd_scripts] 萌虎摇摇乐 入口在哪 (Issue #11)
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
