### ISSUE TITLE
大佬炸年兽需要优化下，会卡在助力码提交后进不去界面

### ISSUE THREAD

**Issue by 2375399351** [LingFeng0918/jd_scripts#7]
最后一个助力码提交后，就会显示识别不到活动，尝试从悬浮图标进入，然后因为助力码提交后会显示给500爆竹，然后脚本不会自动返回，就一直卡在那，时间长了就直接跳过这个账号

**Comment by LingFeng9527** [comment]
吾爱破解有人偷我代码，让他们更新去吧

**Comment by 2375399351** [comment]
已经去举报了，真离谱……

**Comment by Jes0n** [comment]
大佬，那个偷码的已经给处理了

**Comment by LingFeng0918** [comment]
那就更新一下代码



***@***.***
 
发件人： Jes0n
发送时间： 2022-01-18 17:20
收件人： LingFeng0918/jd_scripts
抄送： Subscribed
主题： Re: [LingFeng0918/jd_scripts] 大佬炸年兽需要优化下，会卡在助力码提交后进不去界面 (Issue #7)
大佬，那个偷码的已经给处理了
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
